apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-restart-alert
  namespace: monitoring-ryan
  labels:
    release: prometheus
spec:
  groups:
  - name: pod-restart.rules
    rules:
    - alert: PodRestartTooManyTimes
      expr: kube_pod_container_status_restarts_total > 5
      for: 0s
      labels:
        severity: warning
      annotations:
        summary: "Pod {{ $labels.pod }} restart lebih dari 5x"
        description: "Pod {{ $labels.pod }} di namespace {{ $labels.namespace }} mengalami lebih dari 5 kali restart (langsung firing)."
